# Linear Algebra

In [1]:
import jax.numpy as jnp

In [5]:
A = jnp.arange(6).reshape(3,-1)
A

Array([[0, 1],
       [2, 3],
       [4, 5]], dtype=int32)

In [6]:
A.T

Array([[0, 2, 4],
       [1, 3, 5]], dtype=int32)

In [7]:
A = jnp.arange(6, dtype=jnp.float32).reshape(2, 3)
B = A
A, A + B

(Array([[0., 1., 2.],
        [3., 4., 5.]], dtype=float32),
 Array([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]], dtype=float32))

In [8]:
A*B

Array([[ 0.,  1.,  4.],
       [ 9., 16., 25.]], dtype=float32)

In [14]:
A.shape, A.sum(axis=0).shape

((2, 3), (3,))

In [15]:
A

Array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)

In [17]:
A.cumsum(axis=1)

Array([[ 0.,  1.,  3.],
       [ 3.,  7., 12.]], dtype=float32)

In [22]:
x = jnp.arange(3, dtype=jnp.float32)
y = jnp.ones(3, dtype = jnp.float32)
x,  y

(Array([0., 1., 2.], dtype=float32), Array([1., 1., 1.], dtype=float32))

In [23]:
jnp.dot(x,y)

Array(3., dtype=float32)

In [25]:
B = jnp.ones((3, 4))
A, B

(Array([[0., 1., 2.],
        [3., 4., 5.]], dtype=float32),
 Array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32))

In [27]:
jnp.dot(A,B)

Array([[ 3.,  3.,  3.,  3.],
       [12., 12., 12., 12.]], dtype=float32)

In [28]:
jnp.matmul(A,B)

Array([[ 3.,  3.,  3.,  3.],
       [12., 12., 12., 12.]], dtype=float32)